export const brandName = "Shopperz";

// Home Page Data -----------------------------------------------------------------------------------
import { Truck, Shield, Headphones } from "lucide-react";

export const features = [
  {
    icon: Truck,
    title: "Free Shipping",
    description: "Enjoy free delivery on orders above ₹199.",
  },
  {
    icon: Shield,
    title: "Secure Payment",
    description: "Your transactions are safe and encrypted.",
  },
  {
    icon: Headphones,
    title: "24/7 Support",
    description: "We’re always here to assist you.",
  },
];

export const categories = [
  {
    name: "All",
    slug: "all",
    image:
      "https://i.pinimg.com/1200x/4c/ba/be/4cbabe3c3eb75358edc38cf09282ff84.jpg",
  },
  {
    name: "Electronics",
    slug: "electronics",
    image:
      "https://i.pinimg.com/1200x/e1/22/34/e122343ac7ddb125851689e1fb05cc4a.jpg",
  },
  {
    name: "Accessories",
    slug: "accessories",
    image:
      "https://i.pinimg.com/1200x/35/af/6a/35af6a2c96421a599e52a34c257e4132.jpg",
  },
  {
    name: "Wearables",
    slug: "wearables",
    image:
      "https://i.pinimg.com/474x/c0/21/ef/c021ef014b1e51778b742a6d932a8ae0.jpg",
  },
  {
    name: "Clothing",
    slug: "clothing",
    image:
      "https://i.pinimg.com/1200x/aa/84/b8/aa84b81ef23aad7ab83a7063420f7645.jpg",
  },
  {
    name: "Footwear",
    slug: "footwear",
    image:
      "https://i.pinimg.com/736x/07/bb/68/07bb684ee825cdfe8147167638b37403.jpg",
  },
  {
    name: "Grooming",
    slug: "grooming",
    image:
      "https://i.pinimg.com/1200x/ec/fb/29/ecfb294896bed6b511acea8843042caa.jpg",
  },
  {
    name: "Home",
    slug: "home",
    image:
      "https://i.pinimg.com/1200x/eb/d8/4a/ebd84aee9bd1feddce359d9803236f4b.jpg",
  },
  {
    name: "Fitness",
    slug: "fitness",
    image:
      "https://i.pinimg.com/1200x/1d/f3/ce/1df3ce592d30e4ebb8f7cc547eea5dfa.jpg",
  },
  {
    name: "Stationery",
    slug: "stationery",
    image:
      "https://i.pinimg.com/1200x/f9/d7/69/f9d769625fb6ac3271331cc49209763c.jpg",
  },
  {
    name: "Bags",
    slug: "bags",
    image:
      "https://i.pinimg.com/1200x/94/ea/5c/94ea5c09dd295e631132750d8c6acb6f.jpg",
  },
];

// Products Data -----------------------------------------------------------------------------------
export const mockProducts = [
  {
    id: "1",
    slug: "apple-iphone-15-pro",
    name: "Apple iPhone 15 Pro",
    brand: "Apple",
    description:
      "Apple's latest flagship with A17 Pro chip and a titanium design.",
    category: "Electronics",
    price: 134900,
    originalPrice: 139900,
    currency: "INR",
    image:
      "https://img.clevup.in/301826/1-1708521332360.jpeg?width=600&format=webp",
    rating: 4.9,
    reviewCount: 512,
    inStock: true,
    specs: {
      processor: "Apple A17 Pro",
      material: "Titanium",
      display: "6.1-inch Super Retina XDR",
      camera: "48MP main, 12MP ultra-wide",
      battery: "3200 mAh",
    },
  },
  {
    id: "2",
    slug: "macbook-air-m2-2023",
    name: "MacBook Air M2 (2023)",
    brand: "Generic",
    description: "Lightweight Apple laptop with M2 chip and 18-hour battery.",
    category: "Electronics",
    price: 109990,
    originalPrice: 114900,
    currency: "INR",
    image: "https://m.media-amazon.com/images/I/71RDgtHsREL.jpg",
    rating: 4.8,
    reviewCount: 211,
    inStock: true,
    specs: {
      battery: "Long-lasting",
      processor: "M2",
    },
  },
  {
    id: "3",
    slug: "oneplus-buds-pro-2",
    name: "OnePlus Buds Pro 2",
    brand: "OnePlus",
    description: "Premium TWS earbuds with spatial audio and ANC.",
    category: "Accessories",
    price: 9499,
    originalPrice: 11999,
    currency: "INR",
    image:
      "https://image01-in.oneplus.net/india-oneplus-statics-file/epb/202307/07/kDu3h4CRKX2V1P49.png",
    rating: 4.5,
    reviewCount: 90,
    inStock: true,
    specs: {
      type: "Earbuds",
    },
  },
  {
    id: "4",
    slug: "jbl-go-3-portable-speaker",
    name: "JBL Go 3 Portable Speaker",
    brand: "JBL",
    description:
      "Pocket-sized Bluetooth speaker with punchy bass and waterproof design.",
    category: "Accessories",
    price: 3199,
    originalPrice: 3999,
    currency: "INR",
    image:
      "https://www.harmanaudio.in/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwebdcb63f/pdp//JBL_GO3_Black_Box_Image_1605x1605px.png?sw=550&sh=550",
    rating: 4.6,
    reviewCount: 67,
    inStock: true,
    specs: {
      connectivity: "Bluetooth",
      type: "Speaker",
      resistance: "Waterproof",
    },
  },
  {
    id: "5",
    name: "Mi Power Bank 20000mAh",
    description: "High-capacity power bank with 18W fast charging.",
    price: 1999,
    originalPrice: 2499,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7Ndk4UU3ZpL95sp6dpxPln_alxmwncpf22Q&s",
    category: "Accessories",
    rating: 4.4,
    reviewCount: 122,
    inStock: true,
  },
  {
    id: "6",
    name: "Philips Beard Trimmer",
    description:
      "Cordless trimmer with 45 minutes runtime and skin-friendly blades.",
    price: 1249,
    originalPrice: 1499,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA_tZUn7BfR22i-WzXBfs4j6aJFpJLShs7pfcaeAvmfL_M2F8tQiOkNh-2tKDgkQh9nt8&usqp=CAU",
    category: "Accessories",
    rating: 4.2,
    reviewCount: 143,
    inStock: true,
  },
  {
    id: "7",
    name: "Skybags Black Laptop Backpack",
    description: "Sleek, water-resistant backpack with padded laptop sleeve.",
    price: 1799,
    originalPrice: 2199,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBdRTxz07RGdAyevGZIyzeXEOH6CVn0kW8Xg&s",
    category: "Accessories",
    rating: 4.3,
    reviewCount: 83,
    inStock: true,
  },
  {
    id: "8",
    name: "Noise ColorFit Pulse 2",
    description: "Smartwatch with large display and health tracking features.",
    price: 1799,
    originalPrice: 2999,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjMlupt0t0x3Mj1IMJOxvreDpQKj08e9wolQ&s",
    category: "Wearables",
    rating: 4.1,
    reviewCount: 188,
    inStock: true,
  },
  {
    id: "9",
    name: "boAt Rockerz 255 Pro+ Neckband",
    description: "Bluetooth neckband with ASAP charge and IPX7 rating.",
    price: 1399,
    originalPrice: 1990,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTanvus6NQ9VlRpEj_91l-Z5cP8qYjj03iNog&s",
    category: "Accessories",
    rating: 4.4,
    reviewCount: 250,
    inStock: true,
  },
  {
    id: "10",
    name: "Men’s Black Round Neck T-Shirt",
    description: "Comfortable 100% cotton t-shirt with regular fit.",
    price: 499,
    originalPrice: 699,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTvsRu99jVABXL9n2Vulk_rVve3G0GQHDq_g&s",
    category: "Clothing",
    rating: 4.2,
    reviewCount: 72,
    inStock: true,
  },
  {
    id: "11",
    name: "Roadster Men's Denim Jacket",
    description: "Classic blue denim jacket with button closure.",
    price: 1599,
    originalPrice: 2499,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxWM0S2QAc3zCu9-pnNqQmPqcACKm-Qe5J8A&s",
    category: "Clothing",
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
  },
  {
    id: "12",
    name: "Women’s Sunglasses (Black)",
    description: "UV-protected stylish black round sunglasses.",
    price: 799,
    originalPrice: 1299,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDODAKhIAQ2uHCLgDGs0jQQUlYFM_M6GBmAw&s",
    category: "Accessories",
    rating: 4.1,
    reviewCount: 65,
    inStock: true,
  },
  {
    id: "13",
    name: "Fossil Gen 6 Smartwatch",
    description: "Stylish Android-compatible smartwatch with SpO2 tracking.",
    price: 18999,
    originalPrice: 22999,
    image:
      "https://m.media-amazon.com/images/I/71Vqggkd8hL._UF1000,1000_QL80_.jpg",
    category: "Wearables",
    rating: 4.6,
    reviewCount: 131,
    inStock: true,
  },
  {
    id: "14",
    name: "iPhone 13",
    description: "Value flagship with A15 Bionic chip and great camera system.",
    price: 59999,
    originalPrice: 69999,
    image:
      "https://m.media-amazon.com/images/I/71xb2xkN5qL._UF1000,1000_QL80_.jpg",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 354,
    inStock: true,
  },
  {
    id: "15",
    name: "Apple AirPods (2nd Gen)",
    description: "Easy-to-use wireless earbuds with rich, high-quality sound.",
    price: 10999,
    originalPrice: 12900,
    image:
      "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-pro-2-hero-select-202409_FV1_FMT_WHH?wid=752&hei=636&fmt=jpeg&qlt=90&.v=WTk1dTl5UTBnZXdKN2tua2pFb1hvQ3hmVXd6RnorM2pzUlRIKzNkUEN0UjUvWUFQTXRnUEZqWWRRU2d1WFJwZlcrN05qS3VEVG0zVXZGNUlPVjFnM0RNZGEwYVUyTzcvZlg1UkxwTzJQS1U4K1JOcE5YME4zSHVzMkxMK0ZjVTI",
    category: "Accessories",
    rating: 4.6,
    reviewCount: 213,
    inStock: true,
  },
  {
    id: "16",
    name: "Unisex Slim Leather Wallet",
    description: "Compact wallet with RFID protection and multiple slots.",
    price: 799,
    originalPrice: 999,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoaJOggqfwQE32XSBd5P_o11bomHQn121gVQ&s",
    category: "Accessories",
    rating: 4.3,
    reviewCount: 45,
    inStock: true,
  },
  {
    id: "17",
    name: "Bluetooth Selfie Stick Tripod",
    description: "Adjustable tripod with Bluetooth remote for group selfies.",
    price: 699,
    originalPrice: 1199,
    image: "https://m.media-amazon.com/images/I/51z8dHGMm2L.jpg",
    category: "Accessories",
    rating: 4.0,
    reviewCount: 78,
    inStock: true,
  },
  {
    id: "18",
    name: "Puma Boys Cotton Hoodie",
    description: "Warm hoodie with graphic print and kangaroo pocket.",
    price: 899,
    originalPrice: 1299,
    image:
      "https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/25306216/2023/10/3/019ac03b-75dc-4ffe-91c3-56d1b01973bf1696319051757PumaBoysNo1LogoCelebrationHoodie1.jpg",
    category: "Clothing",
    rating: 4.2,
    reviewCount: 52,
    inStock: true,
  },
  {
    id: "19",
    name: "Women’s Analog Watch",
    description: "Minimal wristwatch with metallic strap for casual wear.",
    price: 1299,
    originalPrice: 1999,
    image:
      "https://www.carlington.in/cdn/shop/files/Carlington_elite_analog_ladies_watch_CT_2014_silver.jpg?v=1696691305",
    category: "Accessories",
    rating: 4.3,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: "20",
    name: "Wireless Charging Pad",
    description: "Fast wireless charger compatible with Android & iPhones.",
    price: 899,
    originalPrice: 1399,
    image:
      "https://www.belkin.com/dw/image/v2/BGBH_PRD/on/demandware.static/-/Sites-master-product-catalog-blk/default/dw784b55c7/images/hi-res/6/152404694_WIZ021ttBK_FPK_WEB.jpg?sfrm=png",
    category: "Accessories",
    rating: 4.4,
    reviewCount: 120,
    inStock: true,
  },
  {
    id: "21",
    name: "Redmi Note 13 Pro+ 5G",
    description: "Mid-range smartphone with curved AMOLED and 200MP camera.",
    price: 31999,
    originalPrice: 34999,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTwSpLLWPFY9wN0ppQvZvroyjQmN_bHjwJyw&s",
    category: "Electronics",
    rating: 4.5,
    reviewCount: 88,
    inStock: true,
  },
  {
    id: "22",
    name: "Casual Sneakers for Men",
    description: "Comfortable lace-up shoes for everyday wear.",
    price: 1099,
    originalPrice: 1499,
    image:
      "https://kxadmin.metroshoes.com/product/71-8805-16-40/1200/71-8805LA16.jpg",
    category: "Clothing",
    rating: 4.1,
    reviewCount: 39,
    inStock: true,
  },
  {
    id: "23",
    name: "Neck Pillow Travel Set",
    description: "Memory foam neck pillow with eye mask and earplugs.",
    price: 699,
    originalPrice: 899,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkrSZ1Js196gTUZgBTEihzDIAvMI-_zqLkYg&s",
    category: "Accessories",
    rating: 4.0,
    reviewCount: 55,
    inStock: true,
  },
  {
    id: "24",
    name: "Women’s Kurti Set",
    description:
      "Cotton printed kurti with palazzo for festive and daily wear.",
    price: 1499,
    originalPrice: 1999,
    image: "https://m.media-amazon.com/images/I/817kSlvA50L._UY1100_.jpg",
    category: "Clothing",
    rating: 4.2,
    reviewCount: 63,
    inStock: true,
  },
  {
    id: "25",
    name: "Lenovo Wireless Keyboard & Mouse Combo",
    description: "Stylish combo set with smooth keys and ergonomic design.",
    price: 1799,
    originalPrice: 2199,
    image:
      "https://store.lenovo.com/media/catalog/product/cache/90c9f6aca4e4b4913161c59294bbd070/4/X/4X30M39458-0.webp",
    category: "Accessories",
    rating: 4.3,
    reviewCount: 70,
    inStock: true,
  },
  {
    id: "26",
    name: "Puma Running Shoes",
    description: "Breathable and lightweight shoes for daily workouts.",
    price: 2499,
    originalPrice: 3499,
    image:
      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/377758/01/sv01/fnd/IND/fmt/png/ForeverRun-NITRO%E2%84%A2-Women's-Running-Shoes",
    category: "Footwear",
    rating: 4.3,
    reviewCount: 84,
    inStock: true,
  },
  {
    id: "27",
    name: "Beardo Hair Wax",
    description: "Strong hold hair wax for men, matte finish.",
    price: 299,
    originalPrice: 399,
    image:
      "https://beardo.in/cdn/shop/files/Beardo_ClayWax_A__Banner_2160x2160_09.jpg?v=1697095561&width=1946",
    category: "Grooming",
    rating: 4.2,
    reviewCount: 33,
    inStock: true,
  },
  {
    id: "28",
    name: "Cello Hot Flask 1L",
    description: "Stainless steel insulated bottle to keep drinks hot/cold.",
    price: 699,
    originalPrice: 999,
    image: "https://m.media-amazon.com/images/I/81elEZiyPfL.jpg",
    category: "Home",
    rating: 4.5,
    reviewCount: 70,
    inStock: true,
  },
  {
    id: "29",
    name: "Nivia Football",
    description: "Durable synthetic rubber football for training & matches.",
    price: 599,
    originalPrice: 899,
    image: "https://nasindia.co/wp-content/uploads/b-n-w.jpg",
    category: "Fitness",
    rating: 4.3,
    reviewCount: 61,
    inStock: true,
  },
  {
    id: "30",
    name: "Classmate Spiral Notebook",
    description: "Hardbound ruled A5 notebook, 200 pages.",
    price: 89,
    originalPrice: 110,
    image: "https://m.media-amazon.com/images/I/71hvNQi9GML.jpg",
    category: "Stationery",
    rating: 4.6,
    reviewCount: 102,
    inStock: true,
  },
  {
    id: "31",
    name: "Fastrack Wallet for Men",
    description: "Bi-fold leather wallet with card holders.",
    price: 899,
    originalPrice: 1299,
    image: "https://m.media-amazon.com/images/I/61W5INJvmWL._UY200_.jpg",
    category: "Bags",
    rating: 4.4,
    reviewCount: 40,
    inStock: true,
  },
  {
    id: "32",
    name: "Samsung Galaxy Tab A9",
    description: "Budget tablet with 8.7-inch display and 5100mAh battery.",
    price: 12499,
    originalPrice: 14999,
    image:
      "https://images.samsung.com/is/image/samsung/p6pim/in/sm-x110nzsains/gallery/in-galaxy-tab-a9-sm-x110-sm-x110nzsains-538450558?$684_547_PNG$",
    category: "Electronics",
    rating: 4.3,
    reviewCount: 130,
    inStock: true,
  },
  {
    id: "33",
    name: "Fire-Boltt Ninja Call Pro Plus",
    description: "Bluetooth calling smartwatch with HD display.",
    price: 1499,
    originalPrice: 2999,
    image:
      "https://images.fonearena.com/blog/wp-content/uploads/2022/11/Fire-Boltt-Ninja-Call-Pro-Plus-1.jpg",
    category: "Wearables",
    rating: 4.2,
    reviewCount: 85,
    inStock: true,
  },
  {
    id: "34",
    name: "Campus Men's Flip Flops",
    description: "Comfortable slip-ons with cushioned sole.",
    price: 499,
    originalPrice: 799,
    image:
      "https://images.jdmagicbox.com/quickquotes/images_main/campus-mens-outdoor-flip-flop-slipper-uk-d-gry-p-grn-272177836-s02by.jpg",
    category: "Footwear",
    rating: 4.0,
    reviewCount: 54,
    inStock: true,
  },
  {
    id: "35",
    name: "L'Oréal Face Wash",
    description: "Deep cleansing face wash for oily skin.",
    price: 199,
    originalPrice: 299,
    image:
      "https://m.media-amazon.com/images/I/51c+BwcRlSL._UF1000,1000_QL80_.jpg",
    category: "Grooming",
    rating: 4.4,
    reviewCount: 69,
    inStock: true,
  },
  {
    id: "36",
    name: "Tupperware Lunch Box",
    description: "Microwave-safe compact lunch box with divider.",
    price: 599,
    originalPrice: 899,
    image:
      "https://www.shoptupperware.in/cdn/shop/files/11167329_01.jpg?v=1741859003",
    category: "Home",
    rating: 4.5,
    reviewCount: 82,
    inStock: true,
  },
  {
    id: "37",
    name: "Skipping Rope with Counter",
    description: "Adjustable fitness rope with digital counter.",
    price: 349,
    originalPrice: 599,
    image:
      "https://m.media-amazon.com/images/I/51Ma0GnTtYL._UF894,1000_QL80_.jpg",
    category: "Fitness",
    rating: 4.1,
    reviewCount: 45,
    inStock: true,
  },
  {
    id: "38",
    name: "Pilot V5 Hi-Tecpoint Pen",
    description: "Smooth writing gel pen for professionals.",
    price: 60,
    originalPrice: 80,
    image:
      "https://statmo.in/wp-content/uploads/2017/03/Pilot-Hi-Tecpoint-V5-Pen-min.jpg",
    category: "Stationery",
    rating: 4.7,
    reviewCount: 90,
    inStock: true,
  },
  {
    id: "39",
    name: "Wildcraft Sling Bag",
    description: "Compact sling bag for travel and casual use.",
    price: 799,
    originalPrice: 1099,
    image:
      "https://images-static.nykaa.com/media/catalog/product/4/e/4ee584212439_Green_3.jpg?tr=w-500",
    category: "Bags",
    rating: 4.2,
    reviewCount: 66,
    inStock: true,
  },
  {
    id: "40",
    name: "iPhone 15 Clear Case",
    description: "Slim transparent case with shockproof corners.",
    price: 499,
    originalPrice: 699,
    image:
      "https://www.capesindia.com/cdn/shop/files/Artboard_8_c0f7cba6-50e3-4e75-a861-74dadc9e350a.jpg?v=1741170210&width=2002",
    category: "Accessories",
    rating: 4.3,
    reviewCount: 37,
    inStock: true,
  },
  {
    id: "41",
    name: "Men’s Formal White Shirt",
    description: "Classic button-down shirt, perfect for office.",
    price: 1199,
    originalPrice: 1499,
    image:
      "https://ramrajcotton.in/cdn/shop/files/1_423aad6e-f58d-4be7-b85c-21e3bbb5085c.jpg?v=1718081032",
    category: "Clothing",
    rating: 4.5,
    reviewCount: 91,
    inStock: true,
  },
  {
    id: "42",
    name: "Logitech M331 Silent Mouse",
    description: "Silent click wireless mouse with long battery.",
    price: 1099,
    originalPrice: 1499,
    image: "https://etopia.hk/wp-content/uploads/2025/03/LOGM331-01.jpg",
    category: "Electronics",
    rating: 4.6,
    reviewCount: 140,
    inStock: true,
  },
  {
    id: "43",
    name: "Digital Alarm Clock",
    description: "LED display with snooze and temperature.",
    price: 799,
    originalPrice: 1099,
    image:
      "https://xech.com/cdn/shop/files/xechclockseon-309078.jpg?v=1734843554&width=1445",
    category: "Home",
    rating: 4.1,
    reviewCount: 76,
    inStock: true,
  },
  {
    id: "44",
    name: "Reebok Gym Bag",
    description: "Spacious duffle bag with separate shoe compartment.",
    price: 1499,
    originalPrice: 1999,
    image: "https://imagescdn.reebok.in/img/app/product/7/781619-9057946.jpg",
    category: "Bags",
    rating: 4.4,
    reviewCount: 63,
    inStock: true,
  },
  {
    id: "45",
    name: "Dettol Hand Wash (500ml)",
    description: "Kills 99.9% germs with moisturizers.",
    price: 119,
    originalPrice: 149,
    image:
      "https://cdn.mafrservices.com/sys-master-root/he3/h53/51229733486622/979472_main.jpg?im=Resize=480",
    category: "Grooming",
    rating: 4.7,
    reviewCount: 150,
    inStock: true,
  },
  {
    id: "46",
    name: "Anker USB-C Fast Charger",
    description: "20W USB-C charger compatible with iPhone & Android.",
    price: 1299,
    originalPrice: 1599,
    image:
      "https://mx2games.com/wp-content/uploads/2024/09/Anker-Nano-Charger-100W-With-USB-C-Cable-Shell-White-A2679-httpsmx2games.com_.png",
    category: "Accessories",
    rating: 4.6,
    reviewCount: 77,
    inStock: true,
  },
  {
    id: "47",
    name: "Mens Slim Fit Blazer",
    description: "Stylish navy blue blazer for formal occasions.",
    price: 2999,
    originalPrice: 3599,
    image:
      "https://imagescdn.louisphilippe.com/img/app/product/9/907507-11192350.jpg?auto=format&w=390",
    category: "Clothing",
    rating: 4.5,
    reviewCount: 102,
    inStock: true,
  },
  {
    id: "48",
    name: "Hiking Water Bottle Clip",
    description: "Metal hook for water bottle attachment to bags.",
    price: 199,
    originalPrice: 299,
    image:
      "https://bluearmy.co.in/cdn/shop/files/1_4747e693-ac0c-4740-8ddd-be65d3ecfc7f.png?v=1747057857",
    category: "Accessories",
    rating: 4.2,
    reviewCount: 36,
    inStock: true,
  },
  {
    id: "49",
    name: "Yoga Mat Non-Slip 6mm",
    description: "Durable & cushioned mat for yoga and stretching.",
    price: 1099,
    originalPrice: 1499,
    image:
      "https://www.jiomart.com/images/product/original/494240937/cockatoo-yoga-mat-tpe-non-slip-6mm-purple-product-images-o494240937-p605443559-1-202401241858.jpg?im=Resize=(420,420)",
    category: "Fitness",
    rating: 4.4,
    reviewCount: 98,
    inStock: true,
  },
  {
    id: "50",
    name: "Notebook Combo Pack (5)",
    description: "Set of 5 longbooks with attractive covers.",
    price: 199,
    originalPrice: 250,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4WXdZae05UGm5UcUM7brml-Y8Xh3jh2mghg&s",
    category: "Stationery",
    rating: 4.6,
    reviewCount: 88,
    inStock: true,
  },
];
